### PR TITLE
Closes #36; File Uploads Not Working

### LINKED ISSUE #36: File Uploads Not Working [$10]
Can't upload a file from the device, no errors displayed or anything.
## <bountysource-plugin>

Did you help close this issue? Go claim the **[$10 bounty](https://www.bountysource.com/issues/28679255-file-uploads-not-working?utm_campaign=plugin&utm_content=tracker%2F21834450&utm_medium=issues&utm_source=github)** on [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21834450&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pschonder**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@pschonder that's all the issue was?

**Comment by pschonder** [comment]
I fixed this issue some time ago when the app was part of the "Server-Repo". An hour ago I had the brainwave and remembered the solution.

**Comment by geekgonecrazy** [comment]
You rock!  Thanks for the PR :smile:

**Comment by pschonder** [comment]
Thanks. Let's see if this one fixes the problem for all of us.

**Comment by Burstaholic** [comment]
Great! This fixes one of the biggest annoyances in the Cordova version. Note: this worked for me in the emulator, so it's not just you anyway.

**Comment by rodrigok** [comment]
I don't believe that the solution is so simple, I spent a lot of hours trying to solve this problem.

Thank you so much :smiley:

**Pull request merged**
