### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Ref #69 

@valessiobrito / @mrplow

Can you guys give this a once over and verify this is what you had to do to get this to work?

### CODE REVIEW

**Comment by mrplow** [comment]
I believe it should be
sudo npm install cordova coffee-script -g
+npm install ticons underscore

it wouldn't work when I installed ticons globally

**Comment by geekgonecrazy** [comment]
@mrplow if you check the package.json ticons and underscore are already included.  So doing npm install would install those.

**Comment by mrplow** [comment]
You would think so, but thats not what I've found on my end.
Ubuntu 15.10 x64 oracle java 8

**Comment by geekgonecrazy** [comment]
@mrplow added a troubleshooting section with those steps.

**Pull request merged**
