### PR TITLE
Allow server switching during Easy Share action

### PR DESCRIPTION
**Pull request by Burstaholic**
This uses a temporary file to store the Share Intent's information while the WebView navigates, then goes into the same room choosing flow.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Sweet!  I'm guessing this fits nicely with #64

You rock!

**Comment by geekgonecrazy** [comment]
@Burstaholic the update to cross walk almost slipped by with out me noticing.  :smile: does the update in version change compatibility with any version of Android?

**Comment by Burstaholic** [comment]
No; I also tried it via emulator in the oldest Android version Crosswalk supports at all (4.0) and it worked fine. I'm hoping there might even be some performance improvement for the older devices.

**Comment by geekgonecrazy** [comment]
ok cool!  :)

@RocketChat/core 

After someone else takes a look, we need to merge and cut a release with the new sharing feature.  :+1:

**Comment by rodrigok** [comment]
LGTM

**Comment by rodrigok** [comment]
captura de tela 2016-02-19 as 16 32 55

I have no idea why :(

**Comment by geekgonecrazy** [comment]
@Burstaholic what version of android are you trying in the emulator?  Rodrigo's is 5.1 it looks like and crashing.

**Pull request merged**
